import { fetchApi } from "./client";

export interface TransformationResponse {
  step_id: string;
  transformed_code: string;
  status: "completed" | "failed" | "in_progress";
}

export const triggerTransformation = async (
  projectId: string,
  stepId: string
): Promise<TransformationResponse> => {
  try {
    return await fetchApi<TransformationResponse>(
      `/projects/${projectId}/steps/${stepId}/transform`,
      { method: "POST" }
    );
  } catch (_err) {
    console.warn(`[MOCK_FALLBACK] Backend transformation endpoint unavailable; returning mock transformation for step ${stepId}.`);
    return {
      step_id: stepId,
      transformed_code: `// Transformed Target Module for Step: ${stepId}\n// Generated by EMA Backend Orchestration Engine\n\npub struct ModuleHandler {\n    pub id: String,\n}\n\npub async fn handle_request() -> &'static str {\n    "Transformation verified"\n}`,
      status: "completed",
    };
  }
};

export const getTransformationStatus = async (
  projectId: string
): Promise<{ stage: string; progress: number }> => {
  try {
    return await fetchApi<{ stage: string; progress: number }>(
      `/projects/${projectId}/transform/status`
    );
  } catch (_err) {
    console.warn(`[MOCK_FALLBACK] Backend status endpoint unavailable; returning mock transformation status for ${projectId}.`);
    return {
      stage: "transforming",
      progress: 100,
    };
  }
};
