import type { BlueprintStep } from "../types/contracts";
import { getProjectSourceCode } from "../api/project";
import { generateRustCodeFromJava } from "../api/transform";

export const stripRustComments = (code: string): string => {
  let result = "";
  let inString = false;
  let stringChar = "";
  let i = 0;

  while (i < code.length) {
    const char = code[i];
    const nextChar = code[i + 1];

    if (inString) {
      result += char;
      if (char === "\\" && nextChar) {
        result += nextChar;
        i += 2;
        continue;
      }
      if (char === stringChar) {
        inString = false;
      }
      i++;
      continue;
    }

    if (char === '"' || char === "'") {
      inString = true;
      stringChar = char;
      result += char;
      i++;
      continue;
    }

    if (char === "/" && nextChar === "/") {
      i += 2;
      while (i < code.length && code[i] !== "\n" && code[i] !== "\r") {
        i++;
      }
      continue;
    }

    if (char === "/" && nextChar === "*") {
      i += 2;
      while (i < code.length - 1 && !(code[i] === "*" && code[i + 1] === "/")) {
        i++;
      }
      i += 2;
      continue;
    }

    result += char;
    i++;
  }

  return result;
};

export const sanitizeRustCode = (rawCode: string): string => {
  if (!rawCode) return "";

  let code = rawCode.trim();

  // Extract code inside markdown code block if present
  const codeBlockMatch = code.match(/```(?:rust|rs)?\s*([\s\S]*?)```/i);
  if (codeBlockMatch) {
    code = codeBlockMatch[1];
  } else {
    code = code.replace(/```(?:rust|rs)?/gi, "").replace(/```/g, "");
  }

  // Remove invalid macros if any
  code = code.replace(/import_axum_prelude!\s*\(\s*\)\s*;?/g, "");

  // Fix obsolete Axum 0.6 Server::bind API to Axum 0.7 TcpListener::bind + axum::serve
  code = code.replace(
    /axum::Server::bind\(&"([^"]+)"\.parse\(\)\?\)\s*\.serve\(([^)]+)\)\.await\?/g,
    'let listener = tokio::net::TcpListener::bind("$1").await?;\naxum::serve(listener, $2).await?'
  );

  return code.trim();
};

export const downloadCombinedRustProject = (
  projectId: string,
  projectName: string,
  steps: BlueprintStep[]
) => {
  const cleanName = (projectName || "migrated_service")
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_");

  const watermark = `// Generated by EMA Migration Engine (${cleanName})`;

  const extractedCodeChunks: string[] = [];

  steps.forEach((step) => {
    if (step.target_pattern && !step.target_pattern.includes("Click 'Transform Step'")) {
      const sanitized = sanitizeRustCode(step.target_pattern);
      if (sanitized) {
        extractedCodeChunks.push(sanitized);
      }
    }
  });

  if (extractedCodeChunks.length === 0) {
    const srcMap = getProjectSourceCode(projectId);
    const rawJavaCode = Object.values(srcMap).join("\n") || "";
    const generated = generateRustCodeFromJava(rawJavaCode, "combined");
    extractedCodeChunks.push(generated);
  }

  let rawCombined = extractedCodeChunks.join("\n\n");

  // Check if main function or Axum web service features are present
  const hasMainFunction = /\b(async\s+)?fn\s+main\b/.test(rawCombined);
  const isAxumService = /\b(axum|Router|TcpListener|serve)\b/.test(rawCombined);

  if (!hasMainFunction) {
    if (isAxumService) {
      const defaultAxumMain = `use axum::{routing::get, Router};

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/health", get(|| async { "OK" }));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000")
        .await
        .unwrap();

    axum::serve(listener, app).await.unwrap();
}`;
      rawCombined = `${defaultAxumMain}\n\n${rawCombined}`;
    }
  } else {
    // Deduplicate main() functions if multiple main functions were provided
    const mainRegex = /(?:#\[tokio::main\]\s*)?(?:async\s+)?fn\s+main\s*\(\s*\)\s*(?:->[^{]+)?\{[\s\S]*?\}/g;
    let mainCount = 0;
    rawCombined = rawCombined.replace(mainRegex, (match) => {
      mainCount++;
      return mainCount === 1 ? match : "";
    });
  }

  // Deduplicate imports
  const lines = rawCombined.split("\n");
  const seenImports = new Set<string>();
  const outputLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("use ")) {
      if (seenImports.has(trimmed)) {
        continue;
      }
      seenImports.add(trimmed);
    }
    outputLines.push(line);
  }

  const cleanedBody = sanitizeRustCode(outputLines.join("\n"));

  const finalContent = `${watermark}\n\n${cleanedBody}\n`;

  const blob = new Blob([finalContent], { type: "text/rust;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${cleanName}_migrated_main.rs`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const downloadCargoToml = (projectName: string) => {
  const cleanName = (projectName || "migrated_service")
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_");

  const cargoContent = `[package]
name = "${cleanName}"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
`;

  const blob = new Blob([cargoContent], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "Cargo.toml";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

